name: LLEN_LOL_v1
model_type: ImageCleanModel
scale: 1
num_gpu: 1  
manual_seed: 100

datasets:
  train:
    name: TrainSet
    type: Dataset_PairedImage
    dataroot_gt: data/LOLv1/Train/target
    dataroot_lq: data/LOLv1/Train/input
    geometric_augs: true

    filename_tmpl: '{}'
    io_backend:
      type: disk

    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 8

    mini_batch_sizes: [8]   
    iters: [30000]
    gt_size: 128   
    gt_sizes: [128]

    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: ValSet
    type: Dataset_PairedImage
    dataroot_gt: data/LOLv1/Test/target
    dataroot_lq: data/LOLv1/Test/input
    io_backend:
      type: disk

network_g:
  type: LLEN
  in_channels: 3
  out_channels: 3
  n_feat: 40
  stage: 1
  num_blocks: [2,2,2]

path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

train:
  total_iter: 15000
  warmup_iter: -1
  use_grad_clip: true

  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [4600, 10400]
    restart_weights: [1,1]
    eta_mins: [0.0003,0.000001]   
  
  mixing_augs:
    mixup: true
    mixup_beta: 1.2
    use_identity: true

  optim_g:
    type: Adam
    lr: !!float 2e-4
    betas: [0.9, 0.999]
  
  pixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean

val:
  window_size: 4
  val_freq: !!float 1e2
  save_img: false
  rgb2bgr: true
  use_image: false
  max_minibatch: 8

  metrics:
    psnr: 
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

logger:
  print_freq: 500
  save_checkpoint_freq: !!float 1e2
  use_tb_logger: true
  wandb:
    project: low_light
    resume_id: ~

dist_params:
  backend: nccl
  port: 29500
